name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]  # Use the appropriate OS for your setup
    runs-on: ${{ matrix.os }}

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mystore
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
          - 8889:3306  # Map container's port 3306 to host's port 8889
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "BASE_URL=http://localhost:8888/mystore/" >> $GITHUB_ENV
          echo "BROWSER=headlesschrome" >> $GITHUB_ENV
          echo "DB_PORT=8889" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_DATABASE=mystore" >> $GITHUB_ENV
          echo "DB_TABLE_PREFIX=wp_" >> $GITHUB_ENV
          echo "WOO_KEY=${{ secrets.WOO_KEY }}" >> $GITHUB_ENV
          echo "WOO_SECRET=${{ secrets.WOO_SECRET }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: List directory contents
        run: |
          ls -R ${{ github.workspace }}

      - name: Run backend tests
        run: |
          pytest ${{ github.workspace }}/mystore_automation/tests/backend
        env:
          DB_HOST: localhost
          DB_PORT: 8889  # Ensure this matches the port mapping
          DB_USER: root
          DB_PASSWORD: root
          DB_DATABASE: mystore
